# Generated by Django 4.2.5 on 2023-10-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='email'),
        ),
    ]
